### PR TITLE
ci: upgrade workflows to v4.x

### LINKED ISSUE #15: Upgrade CCC workflows to 4.x

### PR DESCRIPTION
**Pull request by athomas-ccc**
Closes #15

### CODE REVIEW

**Comment by athomas-ccc** [comment]
@mmcgehee-ccc should I add the `closes-issue-check` and `semantic-pull-request-title` steps to the `ci.yml` workflow? I suspect those are more newly-developed checks that probably just didn't get added to this repo's CI yet.

**Comment by athomas-ccc** [comment]
Tested [here](https://github.com/cccteam/civil/actions/runs/9614765167). Test results successful.

**Comment by mmcgehee-ccc** [comment]
> @mmcgehee-ccc should I add the `closes-issue-check` and `semantic-pull-request-title` steps to the `ci.yml` workflow? I suspect those are more newly-developed checks that probably just didn't get added to this repo's CI yet.

I don't think we are requiring the `closes-issue-check` in these cccteam repos, but yes to the `semantic-pull-request-title`.

**Review by mmcgehee-ccc — APPROVED** [review]
LGTM

**Pull request merged**
